var hi : $(mode.normal: hitam)
var me : $(mode.bold: merah)
var cy : $(mode.bold: cyan)
var ku : $(mode.bold: kuning)
var bi : $(mode.bold: biru)
var ij : $(mode.bold: hijau)
var m : $(mode.bold: pink)
var pu : $(mode.bold: putih)
var st : $(default.color)
